# Generated by Django 5.2.6 on 2025-10-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(max_length=50)),
                ('cap', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
