# Generated by Django 5.2.6 on 2025-09-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_floor_alter_room_cap_alter_room_room_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
