# Generated by Django 5.2.6 on 2025-09-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bookable',
        ),
    ]
