# Generated by Django 5.2.6 on 2025-09-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_booking_room_remove_booking_user_delete_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='studentid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
