# Generated by Django 5.2.6 on 2025-09-12 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_room_booking_room_id_booking_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
