name: Unit Tests

on:
  push:
    branches:
      - testing  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3      
      - uses: actions/setup-python@v4  
        with:
          python-version: "3.11"

      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
<<<<<<< HEAD
          python ./manage.py test
=======
          python manage.py test
>>>>>>> a0782d5c83d150192eb0d834900012b7edb381d3
