name: Django Unit Tests and Coverage Report

on:
  push:
    branches:
      - testing  

jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3      

      - name: Set up Python
        uses: actions/setup-python@v4  
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run Unit Tests with Coverage
        run: |
          coverage run manage.py test
          coverage report
